#!/usr/bin/env node
// Writes THIRD_PARTY_NOTICES.md: every package that ships inside the app (the dependencies in
// package.json and everything they depend on), with its licence and copyright notice, followed
// by the licence texts. Run it after changing dependencies: `pnpm notices`.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
const root = path.resolve('.');
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));

/** Where a dual licence offers a choice, the one this project takes. */
const CHOSEN = {
  '(MIT OR GPL-3.0-or-later)': 'MIT',
  '(MPL-2.0 OR Apache-2.0)': 'Apache-2.0',
};

function dirOf(name, from) {
  try {
    return path.dirname(require.resolve(`${name}/package.json`, { paths: [from] }));
  } catch {
    try {
      let dir = path.dirname(require.resolve(name, { paths: [from] }));
      for (;;) {
        const file = path.join(dir, 'package.json');
        if (existsSync(file) && JSON.parse(readFileSync(file, 'utf8')).name === name) return dir;
        const up = path.dirname(dir);
        if (up === dir) return undefined;
        dir = up;
      }
    } catch {
      return undefined;
    }
  }
}

const licenceFile = (dir) => readdirSync(dir).find((n) => /^(licen[sc]e|copying)(\.|$)/i.test(n));

const found = new Map();
function walk(name, from) {
  const dir = dirOf(name, from);
  if (!dir) return;
  const p = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8'));
  if (found.has(p.name)) return;
  const file = licenceFile(dir);
  const text = file ? readFileSync(path.join(dir, file), 'utf8').trim() : '';
  const declared = typeof p.license === 'string' ? p.license : 'see package';
  const copyright = text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => /^(copyright|\(c\)|©)/i.test(l))
    .slice(0, 3);
  const repo = typeof p.repository === 'string' ? p.repository : (p.repository?.url ?? '');
  found.set(p.name, {
    name: p.name,
    version: p.version,
    declared,
    licence: CHOSEN[declared] ?? declared,
    copyright,
    text,
    url: p.homepage || repo.replace(/^git\+/, '').replace(/\.git$/, ''),
  });
  for (const d of Object.keys(p.dependencies ?? {})) walk(d, dir);
}
for (const d of Object.keys(pkg.dependencies ?? {})) walk(d, root);

const all = [...found.values()].sort((a, b) => a.name.localeCompare(b.name));
const fonts = all.filter((p) => p.licence === 'OFL-1.1');
const code = all.filter((p) => p.licence !== 'OFL-1.1');
const families = [...new Set(code.map((p) => p.licence))].sort();

const out = [];
out.push('# Third-party notices', '');
out.push(
  'Shoulder is released under the MIT License (see [LICENSE](LICENSE)). It includes the open-source software and fonts listed here, each under its own licence. This file is generated by `pnpm notices`; do not edit it by hand.',
  '',
  'The Mac app is built with [Electron](https://www.electronjs.org/) (MIT License), which includes Chromium and Node.js. Their notices are inside the app, in `Contents/Resources`, as `LICENSE.electron.txt` and `LICENSES.chromium.html`, next to copies of this file and the LICENSE.',
  '',
);
out.push('## Software', '');
out.push('| Package | Version | Licence | Copyright |', '| --- | --- | --- | --- |');
for (const p of code) {
  const note = p.declared !== p.licence ? ` (offered as ${p.declared.replace(/[()]/g, '')})` : '';
  const who = p.copyright.join('; ').replace(/\|/g, '/') || 'see the package';
  out.push(
    `| ${p.url ? `[${p.name}](${p.url})` : p.name} | ${p.version} | ${p.licence}${note} | ${who} |`,
  );
}
out.push('', '## Fonts', '');
out.push(
  'The bundled fonts are under the SIL Open Font License 1.1. They are distributed unmodified, with their own copyright notices and reserved font names:',
  '',
);
for (const p of fonts) {
  out.push(
    `### ${p.name} ${p.version}`,
    '',
    '```text',
    p.text || 'SIL Open Font License 1.1',
    '```',
    '',
  );
}
out.push('## Licence texts', '');
out.push(
  'One copy of each licence that applies to the software above. The copyright notice for each package is in the table; where a package ships a notice of its own, that notice governs.',
  '',
);
for (const licence of families) {
  const sample = code.find((p) => p.licence === licence && p.text);
  out.push(`### ${licence}`, '');
  if (sample)
    out.push(`As distributed with ${sample.name}:`, '', '```text', sample.text, '```', '');
  else
    out.push(
      `See https://spdx.org/licenses/${licence.replace(/[()]/g, '').split(' ')[0]}.html`,
      '',
    );
}
writeFileSync('THIRD_PARTY_NOTICES.md', out.join('\n'));
console.log(
  `Wrote THIRD_PARTY_NOTICES.md: ${code.length} packages, ${fonts.length} fonts, ${families.length} licences.`,
);
